### ISSUE TITLE
Fans stay off after resuming from suspend

### ISSUE THREAD

**Issue by AFWL** [ilya-zlobintsev/LACT#324]
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Bug description

GPU fans do not turn back on after resuming from suspend. This issue has only been happening recently.

![2024-05-08-234554_hyprshot](https://github.com/ilya-zlobintsev/LACT/assets/118402551/1e9cc104-286a-427a-94b7-183ef5dd80dc)

Debug Snapshot:
[LACT-sysfs-snapshot-20240508-234743.tar.gz](https://github.com/ilya-zlobintsev/LACT/files/15255733/LACT-sysfs-snapshot-20240508-234743.tar.gz)

### System info

```markdown
- LACT version: 0.5.4-release (commit VERGEN_IDEMPOTENT_OUTPUT)
- GPU model: AMD Radeon RX 6600
- Kernel version: 6.8.9-arch1-1
- Distribution: Arch Linux
```

**Comment by ilya-zlobintsev** [comment]
Should be fixed with https://github.com/ilya-zlobintsev/LACT/commit/aa670be9d6ef28a0b738abc42c3ef9e4112b6752 (you can try it either via the [test build](https://github.com/ilya-zlobintsev/LACT/releases/tag/test-build) or the `lact-git` AUR package)

**Comment by AFWL** [comment]
Installed the git version and restarted, but the issue persists:

![2024-05-11-234843_hyprshot](https://github.com/ilya-zlobintsev/LACT/assets/118402551/f6a9a252-8a4d-416e-a3d9-cb0698f8d2b0)

Lact Info:
```
GUI: 0.5.5
Daemon: 0.5.5
```

**Comment by AFWL** [comment]
Despite still being on 0.5.4, this error is no longer happening, therefore I will close this issue. For anyone else still having this issue, I suspect that coolercontrol might have something to do with it, but I haven't investigated.
