### ISSUE TITLE
Maximum VRAM Clock is not set

### ISSUE THREAD

**Issue by theromi** [ilya-zlobintsev/LACT#367]
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Bug description

I set the "Maximum VRAM Clock" to 1350MHz in LACT (2700 works fine in Windows), but the clock won't exceed the standard 1250 MHz (even under 100% load). My settings:

![Screenshot_20240905_102229](https://github.com/user-attachments/assets/b62fa368-6b30-45de-bf92-dd075b6bdc25)

So I tried upping the "Minimum VRAM Clock" to 1350 as well, but it won't apply:

![Screenshot_20240905_102609](https://github.com/user-attachments/assets/f81e62af-66b8-44f4-8400-5a4ad0c3c559)

dmseg after trying to up the minimum:

`[ 3656.286552] amdgpu 0000:0b:00.0: amdgpu: Invalid setting: UclkFmin(1350) is bigger than UclkFmax(1250)`

So I suppose the maximum vram clock is not set correctly. There is no error popup or message in dmseg after trying to set the maximum clock.

[LACT-sysfs-snapshot-20240905-095304.tar.gz](https://github.com/user-attachments/files/16886231/LACT-sysfs-snapshot-20240905-095304.tar.gz)

### System info

```markdown
- LACT version: 0.5.5-release
- GPU model: AMD Radeon RX 7900 XTX
- Kernel version: 6.10.8
- Distribution: CachyOS (Arch Linux)
```

**Comment by ilya-zlobintsev** [comment]
> [ 3656.286552] amdgpu 0000:0b:00.0: amdgpu: Invalid setting: UclkFmin(1350) is bigger than UclkFmax(1250)

> So I suppose the maximum vram clock is not set correctly. There is no error popup or message in dmseg after trying to set the maximum clock.

The reason for this is because the following happens when applying settings:
- Reset previous settings
- Write minimum clock
- Write maximum clock
- Commit settings

It appears that with RDNA3 the max > min check is performed on the write stage, and not on the commit stage like in previous generations, so setting a minimum clock that's above the default maximum doesn't work.

I'll add a workaround so that the write order is swapped in this situation.

**Comment by ilya-zlobintsev** [comment]
Should be fixed with https://github.com/ilya-zlobintsev/LACT/commit/92fad92e37b6b6e53d590f7e0591271053855eee, please try the git build

**Comment by theromi** [comment]
Indeed, the current git build doesn't throw the error message anymore when setting the minimum VRAM clock. Thanks for the fast fix!

It still doesn't seem to go to 2700MHz, even when setting 2700 as the minimum:

![Screenshot_20240909_154138](https://github.com/user-attachments/assets/3c9a70f8-0c66-43da-a436-26161cff7d31)

Weirdly, it goes to 1544MHz (?). Setting the minimum to 2500 and the maximum to 2700 constantly keeps it at 2498, as before. Any ideas?

**Comment by ilya-zlobintsev** [comment]
Have you tried using it under load? Even with the "highest locks" performance level the GPU might decide to partially clock down.

You might also be getting constrained by other factors, such as thermals or power (in the screenshot you have thermal throttling reported, but that might not be accurate as RDNA3 can sometimes falsely report throttling).

**Comment by theromi** [comment]
The screenshot above was taken under 100% load (running CS2 with uncapped fps).

> in the screenshot you have thermal throttling reported, but that might not be accurate as RDNA3 can sometimes falsely report throttling

Yeah, it's always reporting that, even idling at 50°C.

I was playing around with the settings and it gets weirder. Setting the VRAM clock (both min and max) to 2698 works under load and keeps it at a constant 2696 (under load):

![Screenshot_20240909_161908](https://github.com/user-attachments/assets/6f3f0139-5f7d-4298-b065-dcb2b503e383)

But, while idling, it drops to 1544 again and my screen flickers (which does not happen under load). Even more weird: My GPU core clock is now about 200MHz higher (see this screenshot and screenshot above), though I didn't touch that setting at all. This is reproducible and CS2 has about 10% more fps (most likely from GPU clock increase). I don't know what is happening, but I guess it's more amdgpus fault than LACT?

**Comment by ilya-zlobintsev** [comment]
After the settings are applied, all further behaviour is up to the GPU firmware. There isn't much you can do to control it further unfortunately.

**Comment by ilya-zlobintsev** [comment]
I'll close this as the original problem with the setting not applying was fixed.
