### ISSUE TITLE
[v6.0] Power level mode not listing all avail power modes

### ISSUE THREAD

**Issue by knipp30** [ilya-zlobintsev/LACT#427]
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation. Examples of known driver-side issues are fans not turning on with a custom curve or inaccurate power limits on RDNA3.
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Bug description

From the command line, I see the following:
~~~
$ cat /sys/class/drm/card1/device/pp_power_profile_mode
                              0 BOOTUP_DEFAULT* 1 3D_FULL_SCREEN  2 POWER_SAVING    3 VIDEO           4 VR              5 COMPUTE         6 CUSTOM          7 WINDOW_3D       
~~~

However, in LACT, only BOOTUP_DEFAULT is shown
[LACT-sysfs-snapshot-20241203-163118.tar.gz](https://github.com/user-attachments/files/17999348/LACT-sysfs-snapshot-20241203-163118.tar.gz)

### System info

```markdown
- LACT version:6.0
- GPU model: AMD RX7700S
- Kernel version: 6.11.10-300.fc41.x86_64
- Distribution: Fedora 41
```

**Comment by knipp30** [comment]
Just checking - is there anything I provide to help with this?

**Comment by ilya-zlobintsev** [comment]
No need, the snapshot is enough. However, it looks like the format of that file is completely different to desktop GPUs. It's split into columns, instead of rows like on desktop cards.

Format from your snapshot:
```
                              0 BOOTUP_DEFAULT* 1 3D_FULL_SCREEN  2 POWER_SAVING    3 VIDEO           4 VR              5 COMPUTE         6 CUSTOM          7 WINDOW_3D       
Gfx_ActiveHystLimit           0                 0                 0                 0                 0                 0                 0                 0                 
Gfx_IdleHystLimit             0                 2                 0                 0                 1                 1                 0                 2                 
Gfx_FPS                       0                 0                 0                 0                 0                 0                 0                 0                 
Gfx_MinActiveFreqType         1                 1                 1                 1                 4                 4                 1                 1                 
Gfx_BoosterFreqType           4                 4                 3                 4                 1                 1                 4                 4                 
Gfx_MinActiveFreq             0                 0                 0                 0                 1000              1000              0                 0                 
Gfx_BoosterFreq               800               650               0                 0                 0                 0                 800               650               
Fclk_ActiveHystLimit          0                 0                 0                 0                 0                 0                 0                 0                 
Fclk_IdleHystLimit            0                 0                 0                 0                 0                 0                 0                 0                 
Fclk_FPS                      0                 0                 0                 0                 0                 0                 0                 0                 
Fclk_MinActiveFreqType        3                 1                 1                 1                 1                 1                 3                 3                 
Fclk_BoosterFreqType          1                 1                 1                 1                 1                 1                 1                 1                 
Fclk_MinActiveFreq            0                 0                 0                 0                 0                 0                 0                 0                 
Fclk_BoosterFreq              0                 0                 0                 0                 0                 0                 0                 0                 
```

Example from a desktop 7800xt:
```
PROFILE_INDEX(NAME) CLOCK_TYPE(NAME) FPS MinActiveFreqType MinActiveFreq BoosterFreqType BoosterFreq PD_Data_limit_c PD_Data_error_coeff PD_Data_error_rate_coeff
 0 BOOTUP_DEFAULT*:
                    0(       GFXCLK)       0       1       0       4     800 4587520  -65536       0
                    1(         FCLK)       0       3       0       1       0 3276800  -65536   -6553
 1 3D_FULL_SCREEN :
                    0(       GFXCLK)       0       0    1200       4     650 3932160   -3276  -65536
                    1(         FCLK)       0       3       0       3       0 1310720   -6553   -6553
 2   POWER_SAVING :
                    0(       GFXCLK)       0       1       0       3       0 5898240  -65536       0
                    1(         FCLK)       0       1       0       1       0 3407872  -65536   -6553
 3          VIDEO :
                    0(       GFXCLK)       0       1       0       4     500 4587520  -65536       0
                    1(         FCLK)       0       3       0       3       0 3473408  -65536   -6553
 4             VR :
                    0(       GFXCLK)       0       2    1000       1       0 3276800       0       0
                    1(         FCLK)       0       3       0       3       0 1310720   -6553   -6553
 5        COMPUTE :
                    0(       GFXCLK)       0       2    1000       1       0 3932160       0       0
                    1(         FCLK)       0       3       0       3       0 1310720   -6553   -6553
 6         CUSTOM :
                    0(       GFXCLK)       0       0    1200       4       0  655360   -3276  -65536
                    1(         FCLK)       0       3       0       3       0 1310720   -6553   -6553
 7      WINDOW_3D :
                    0(       GFXCLK)       0       0    1200       4     650 3932160   -3276  -65536
                    1(         FCLK)       0       3       0       3       0 1310720   -6553   -6553
```

The parser needs to be updated to be able to handle this. I'll take a look at it.

**Comment by ilya-zlobintsev** [comment]
This should be resolved with https://github.com/ilya-zlobintsev/LACT/commit/7d5d6b96e5c28af5b58a0c5a637226432d2e65e3#diff-fb6e2e6005f75acc8c3dedb4e31109624d224de939ac7e3d3189a17ec95c8884. (You can download the [test build](https://github.com/ilya-zlobintsev/LACT/releases/tag/test-build)).
I've tested this to be parsed correctly. The command format to change the profile seems to be same despite the different table format, so applying should work as well.

Interestingly, according to the issue this format is also used by a RX 7600, which would make sense as it uses the same Navi 33 chip as the 7700s. However it is not the same format as the one used by higher end RDNA3 models like 7800XT or 7900XTX.

**Comment by knipp30** [comment]
I just ran a test - looks like it still doesn't pick up the other options.

I uninstalled the version I was on, installed the new RPM, and restarted the lact service. 

I uploaded a new dump for review.

I am going to give it a reboot as well _just in case_ :)
[LACT-sysfs-snapshot-20241219-193033.tar.gz](https://github.com/user-attachments/files/18204465/LACT-sysfs-snapshot-20241219-193033.tar.gz)
