### ISSUE TITLE
Limited power draw on Manual profil

### ISSUE THREAD

**Issue by Mercvre80** [ilya-zlobintsev/LACT#583]
### Checklist

- [x] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT/wiki/Hardware-Support) as a known limitation. Examples of known driver-side issues are fans not turning on with a custom curve on RDNA3/4 and missing fan control on laptops.
- [x] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration
- [x] I've checked that the issue still happens in the latest [development build](https://github.com/ilya-zlobintsev/lact?tab=readme-ov-file#development-builds).

### Bug description

With the latest release on flathub, I get very poor results when setting the performance level to "Manual". For all the versions I tested, 0.7.3 is the latest that didn't have this bug

I have a set of clocks and power values and multiple benchmarks that I know are stable and replicable. For example on Furmark vk knot, I had 84fps with the following values on lact : manual mode, 3200mhz max core clock, -190mv offset, 300w max power draw limit. When I get back to the 0.7.3 update, both Automatic and Manual mode give that 84fps in furmark as long as I give clockspeed and voltage values

Since 0.7.4 when selecting the performance level as "Manual", on the historical charts it looks like it's limiting the power draw to about 200w, reducing every clock in the process, and I only get about 63/64 fps in furmark. What I found is that when I change the performance level to "Automatic", all the values goes up and I get again the optimal 83/84ish fps in furmark

I guess that the "Automatic" mode, as stated, should adjust values automatically depending on the hardware, while "Manual" mode should just follows user input. But right now I feel like it's either a bug or something is not labeled correctly

### System info

```markdown
- LACT version: 0.7.4
- GPU model: 7900xt
- Kernel version: 6.14
- Distribution: bazzite fedora 42
```

**Comment by positroniumx** [comment]
From kernel documentation for amdgpu:

>auto

>When auto is selected, the driver will attempt to dynamically select the optimal power profile for current conditions in the driver.

and

>manual

>When manual is selected, the user can manually adjust which power states are enabled for each clock domain via the sysfs pp_dpm_mclk, pp_dpm_sclk, and pp_dpm_pcie files and adjust the power state transition heuristics via the pp_power_profile_mode sysfs file.

Unless you are tweaking these values:

![Image](https://github.com/user-attachments/assets/12213908-ad1b-47d3-b01a-5390dfb5bf14)

Then you should be on auto. What I did notice is that selected Power Profile Mode is active in "Auto" as well, so make sure you choose your desired one on Manual,  apply, then move to Auto.
Try tweaking pp_dpm_mclk, pp_dpm_sclk and pp_dpm_pcie values if on manual, maybe that solves your issues?
See:
https://www.kernel.org/doc/html/v6.13-rc1/gpu/amdgpu/thermal.html#pp-dpm
https://wiki.archlinux.org/title/AMDGPU#Manual
It's still not clear, but it does seem that clocks/power level should be adjusted on Manual, but also P-states, which is more obscure for regular users. Tweak your P-states see if that makes a change on manual?

**Comment by Mercvre80** [comment]
ok so if I understand correctly, the 0.7.3 behavior for manual and automatic state was wrong, while the 0.7.4 makes it accurate to what it's really doing ? And that should be more on amdgpu, and not on lact ?
For me this is not a P-states issue, because like you said it's obscure. I never changed them and never had to, so I didn't guess it may be linked to that

**Comment by ilya-zlobintsev** [comment]
This is weird because there were no changes to how AMD settings are written between 0.7.3 and 0.7.4. 0.7.2->0.7.3 was the update that changed how settings work on 7000 series.

How exactly are you testing version changes, is it from flathub or github releases in this repo?

**Comment by Mercvre80** [comment]
`flatpak remote-info --log flathub io.github.ilya_zlobintsev.LACT` gives me the list of the latest updates

`flatpak update --commit=[ID of a specific commit] org.videolan.VLC` let me rollback to various release

and like I said, the behavior of manual and automatic mode changes drastically depending on 0.7.4 (latest) or 0.7.3

![Image](https://github.com/user-attachments/assets/61ef3566-0f22-4eec-a6dc-223f730584bd)

system and user gives me exactly the same output

Just to make myself clear: I have no idea whether this is a bug or an intended feature. I simply believe that the labels used (mainly "automatic") and the change in behavior between versions suggests something is unexpected or unclear for the end user

**Comment by positroniumx** [comment]
Yeap I tested it and indeed it's bad performance on manual.
Lowest clocks also doesn't properly apply. I just noticed you added it.
From my testing, applying lowest clocks is different from Auto. It should be done as last command after setting everything else.
Here's a working example:

```
#!/bin/sh
echo "r" > /sys/class/drm/card1/device/gpu_od/fan_ctrl/fan_curve
echo "r" > /sys/class/drm/card1/device/pp_od_clk_voltage

echo "auto" > /sys/class/drm/card1/device/power_dpm_force_performance_level

echo "0 25 85" > /sys/class/drm/card1/device/gpu_od/fan_ctrl/fan_curve
echo "1 100 85" > /sys/class/drm/card1/device/gpu_od/fan_ctrl/fan_curve
echo "2 100 85" > /sys/class/drm/card1/device/gpu_od/fan_ctrl/fan_curve
echo "3 100 85" > /sys/class/drm/card1/device/gpu_od/fan_ctrl/fan_curve
echo "4 100 85" > /sys/class/drm/card1/device/gpu_od/fan_ctrl/fan_curve

echo "280000000" > /sys/class/drm/card1/device/hwmon/hwmon5/power1_cap
echo "0" > /sys/class/drm/card1/device/pp_power_profile_mode

echo "1" > /sys/class/drm/card1/device/gpu_od/fan_ctrl/fan_zero_rpm_enable
echo "c" > /sys/class/drm/card1/device/gpu_od/fan_ctrl/fan_zero_rpm_enable
echo "c" > /sys/class/drm/card1/device/gpu_od/fan_ctrl/fan_curve

echo "low" > /sys/class/drm/card1/device/power_dpm_force_performance_level
```

I suppose that's the case for Highest clocks as well.
While for "Manual" this works, which is a different order:

```
#!/bin/sh
echo "r" > /sys/class/drm/card1/device/gpu_od/fan_ctrl/fan_curve
echo "r" > /sys/class/drm/card1/device/pp_od_clk_voltage

echo "auto" > /sys/class/drm/card1/device/power_dpm_force_performance_level
echo "manual" > /sys/class/drm/card1/device/power_dpm_force_performance_level

echo "0 25 85" > /sys/class/drm/card1/device/gpu_od/fan_ctrl/fan_curve
echo "1 100 85" > /sys/class/drm/card1/device/gpu_od/fan_ctrl/fan_curve
echo "2 100 85" > /sys/class/drm/card1/device/gpu_od/fan_ctrl/fan_curve
echo "3 100 85" > /sys/class/drm/card1/device/gpu_od/fan_ctrl/fan_curve
echo "4 100 85" > /sys/class/drm/card1/device/gpu_od/fan_ctrl/fan_curve

echo "s 1 3000" > /sys/class/drm/card1/device/pp_od_clk_voltage
echo "m 1 1275" > /sys/class/drm/card1/device/pp_od_clk_voltage
echo "vo -100" > /sys/class/drm/card1/device/pp_od_clk_voltage

echo "280000000" > /sys/class/drm/card1/device/hwmon/hwmon5/power1_cap
echo "0" > /sys/class/drm/card1/device/pp_power_profile_mode
echo "1" > /sys/class/drm/card1/device/gpu_od/fan_ctrl/fan_zero_rpm_enable
echo "c" > /sys/class/drm/card1/device/gpu_od/fan_ctrl/fan_zero_rpm_enable
echo "c" > /sys/class/drm/card1/device/pp_od_clk_voltage
echo "c" > /sys/class/drm/card1/device/gpu_od/fan_ctrl/fan_curve
```

@Mercvre80 Can you test the last one with Manual and confirm it's working fine? Adjust your paths/values to your needs. Would be great if  you could also test the "Lowest clocks" one that's above.

**Comment by Mercvre80** [comment]
I didn't understand what/how/order of operations of what I should test, and on which version of lact, I assume 0.7.4 ? I get that I must enter your given values, but then I don't know what to look for ( better performances, power draw ? ). Also, why is the fan curve involved here. I probably trust the peoples on project such as lact, but I don't want my card to go boom without understanding what is the purpose

I don't have access to my hardware right now but i'll do it on friday/saturday

**Comment by positroniumx** [comment]
@Mercvre80 Card no boom. Nevermind

@ilya-zlobintsev Sure, I'll give it a go later tonight or tomorrow in the morning.

**Comment by positroniumx** [comment]
From what I saw Manual breaks on this commit: https://github.com/ilya-zlobintsev/LACT/commit/c9d286047700bf9db0e30aee4ad7f1dbe53a00af

**Comment by ilya-zlobintsev** [comment]
Please try the latest [test build](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#development-builds), this should be resolved with https://github.com/ilya-zlobintsev/LACT/commit/6e78c7bffee6634122ce903496a9d2af881f2ba8.

**Comment by positroniumx** [comment]
Manual is working fine now. Lowest clocks still doesn't work as it should. GPU clocks should max at 500MHz and memory clocks at 200MHz.
