### ISSUE TITLE
Process Monitor does't show Xorg name

### ISSUE THREAD

**Issue by ManuLinares** [ilya-zlobintsev/LACT#654]
Archlinux
lact 0.8.0-2
linux 6.15.4.arch2-1
nvidia-dkms 575.64.03-1

"Process Monitor" doesn't show Xorg name

![Image](https://github.com/user-attachments/assets/74d6c90c-db70-4a88-9032-b6650b2c1708)

**Comment by ilya-zlobintsev** [comment]
Could you post the output of `readlink /proc/898/exe` and `cat /proc/898/cmdline` (where 898 is the id of  the empty process)

**Comment by ManuLinares** [comment]
```
$ cat /proc/898/cmdline
/usr/lib/Xorg:0-seatseat0-auth/run/lightdm/root/:0-nolistentcpvt7-novtswitch
```

```
$ readlink /proc/898/exe
(notes: no output, when i run "ls" is says Permission denied)
```

```
$ sudo readlink /proc/898/exe
/usr/lib/Xorg
```

shouldn't use `readlink /proc/<PID>/exe`
a working alternative would be `cut -d '' -f1 /proc/<PID>/cmdline`

edit: to clarify I forgot, I am not running the lact daemon, just opened lact in "embedded" mode as it says.

**Comment by ilya-zlobintsev** [comment]
> ```
> $ cat /proc/898/cmdline
> /usr/lib/Xorg:0-seatseat0-auth/run/lightdm/root/:0-nolistentcpvt7-novtswitch
> ```
> 
> ```
> $ readlink /proc/898/exe
> (notes: no output, when i run "ls" is says Permission denied)
> ```
> 
> ```
> $ sudo readlink /proc/898/exe
> /usr/lib/Xorg
> ```
> 
> shouldn't use `readlink /proc/<PID>/exe` a working alternative would be `cut -d '' -f1 /proc/<PID>/cmdline`
> 
> edit: to clarify I forgot, I am not running the lact daemon, just opened lact in "embedded" mode as it says.

> just opened lact in "embedded" mode as it says.

Then this makes sense, as your user does not have the permissions to check the symlink. `exe` is used instead of `cmdline` as it can make a difference for processes with nested runners like wine/proton.

It could use cmdline as a fallback when exe fails though.

**Comment by ManuLinares** [comment]
right, nvidia-smi shows Xorg without needing root elevation.

**Comment by ilya-zlobintsev** [comment]
Resolved in https://github.com/ilya-zlobintsev/LACT/commit/0d65ddb8c0ce18721e8aad3ac656398e03ee08fd

**Comment by ManuLinares** [comment]
this issue is not resolved.

<img width="908" height="632" alt="Image" src="https://github.com/user-attachments/assets/1098b198-ff8c-44af-ac98-249e34152412" />

running lact without the daemon, does't show Xorg name

**Comment by ilya-zlobintsev** [comment]
I am not able to reproduce this with a vulkan process running as root, will try to get an xorg environment running to test it with xorg specifically.

**Comment by ManuLinares** [comment]
> I am not able to reproduce this with a vulkan process running as root, will try to get an xorg environment running to test it with xorg specifically.

the commit you mentioned only touched **lact-daemon/src/server/gpu_controller/common.rs**

**lact-daemon**... I'm not running the daemon. Running lact ui client without the daemon has this issue of not getting the cmdline, to clarify.

**Comment by ilya-zlobintsev** [comment]
> lact-daemon... I'm not running the daemon. Running lact ui client without the daemon

When you run the lact ui without a system daemon, it starts its own daemon instance inside of the ui process. The difference is that it's unprivileged and cannot change hardware settings. So the commit still affects this scenario, but it looks like it's still broken for xorg specifically (it fixed the behaviour with another root process when I was testing it)

**Comment by ilya-zlobintsev** [comment]
I'm still unable to reproduce this with an `Xorg` process running as a different user:

<img width="1220" height="20" alt="Image" src="https://github.com/user-attachments/assets/5eaa6074-0062-4dcf-9302-8ef483e97026" />

```
bash-5.2$ file /proc/45727/exe
/proc/45727/exe: unreadable symlink `/proc/45727/exe' (Permission denied)
bash-5.2$ cat /proc/45727/cmdline 
/usr/libexec/Xorg-nolistentcp-backgroundnone-seatseat0-noreset-keeptty-novtswitch-verbose3-auth/run/user/1001/xauth_rvkHTH-displayfd13vt5
```
Are you currently on version 0.8.1?

**Comment by ManuLinares** [comment]
> Are you currently on version 0.8.1?

My apologies, I was on 0.8.0, this is fixed on 0.8.1.

Thanks.
